---
# tasks file for roles/ansible-role-novnc-install
- name: Update variables
  include_vars: "{{ ansible_distribution }}.yml"

- name: Update system packages
  apt:
    name: "{{ item }}"
    install_recommends: no
    state: present
    update_cache: yes
  with_items:
  - "{{ os_packages }}"
  when: ansible_os_family == "Debian"

- name: Update pip packages
  pip:
    name: "{{ item }}"
    state: present
  with_items:
  - "{{ pip_packages }}"

- name: Download noVNC
  git:
    repo: "{{ novnc_git }}"
    dest: "{{ novnc_folder }}"
    accept_hostkey: True

- name: Set noVNC folder permissions
  file:
    path: "{{ novnc_folder }}"
    state: touch
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Validate that index.html is available for novnc
  stat:
    path: "{{ novnc_folder }}/index.html"
  register: novnc_index

- name: Update with link for index.html if not available
  file:
    src: "{{ novnc_folder }}/vnc.html"
    dest: "{{ novnc_folder }}/index.html"
    state: link
  when: novnc_index.stat.exists == false

- name: Create folders for file copies
  file:
    path: "{{ item }}"
    state: directory
  with_items:
  - /etc/supervisor/conf.d
  - /etc/nginx/sites-available

- name: Setup target folders
  file:
    path: "{{ item.dest | dirname }}"
    state: directory
  with_items:
  - "{{ template_files }}"

- name: Configure servers
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
  - "{{ template_files }}"

- name: Add novnc nginx site
  file:
    dest: /etc/nginx/sites-enabled/novnc-proxy
    src: /etc/nginx/sites-available/novnc-proxy
    state: link

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- block:
  - name: Start Supervisor
    service:
      name: supervisor
      state: restarted
      enabled: yes
  rescue:
    - name: Start Supervisor
      service:
        name: supervisor
        state: restarted
        enabled: yes
