---
# handlers file for roles/ansible-role-novnc-install
- name: Restart Supervisor & Nginx
  service:
    name: "{{ item }}"
    state: restarted
    enabled: yes
  with_items:
  - supervisor
  - nginx
